name: Build and Ship Documentation

on:
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: make setup
      - name: Build Documentation
        run: make build-docs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Store compiled documentation files
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: site

  ship-documentation:
    needs: [build-documentation]
    runs-on: ubuntu-latest
    steps:
      - name: Get documentation site files
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs
      - name: Ship Documentation to Okio Server
        run: echo "TODO"
  

  check:  # This job does nothing and is only used for the branch protection
    if: always()
    needs: [ship-documentation]
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
    